# Render manifest for deploying this repo as a Docker web service.
# Set environment variables (DB, APP_KEY, etc.) in the Render dashboard or replace below with secret names.

services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    # Run migrations during deploy before starting the service
    releaseCommand: php artisan migrate --force
    # Do not hardcode secrets here. Set these in the Render service settings instead.
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://render-deploy-tsm2.onrender.com
      # Example placeholders (do NOT store secrets here in the repository):
      # - key: APP_KEY
      #   value: base64:...
      # - key: DATABASE_URL
      #   value: postgres://USER:PASSWORD@HOST:5432/render_deploy
