# Render manifest for deploying this repo as a Docker web service.
# Set environment variables (DB, APP_KEY, etc.) in the Render dashboard or replace below with secret names.

services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    # Do not hardcode secrets here. Set these in the Render service settings instead.
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://your-render-url.onrender.com
