services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase: mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase: mysql
      - key: DB_USERNAME
        fromDatabase: mysql
      - key: DB_PASSWORD
        fromDatabase: mysql

databases:
  - name: mysql
    plan: free
    databaseName: hungerhop_prod
    user: hungerhop_user
